site_name: Django Live Components
site_url: https://om-proptech.github.io/livecomponents/
repo_url: https://github.com/om-proptech/livecomponents

theme:
  name: material
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

nav:
  - index.md
  - quickstart.md
  - User Guide:
    - livecomponents.md
    - nested_components.md
    - configuration.md
    - javascript_integration.md
    - uploads.md
    - error_handling.md
    - example_project.md
  - Reference:
    - decorators.md
    - templatetags.md
    - management_commands.md
  - Advanced:
    - context.md
    - templates.md
    - component_ids.md
  - About:
      - Changelog: https://github.com/om-proptech/livecomponents/blob/main/CHANGELOG.md

markdown_extensions:
  - pymdownx.superfences
  - pymdownx.details
  - admonition
